# Generated by Django 4.2.11 on 2025-07-20 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_alter_candidateapplication_status'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issortlist',
            name='dateYouApply',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='dateYouApply',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplication'),
        ),
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
